-- Input the db.sql

CREATE DATABASE IF NOT EXISTS sparrow;

USE sparrow;
CREATE TABLE IF NOT EXISTS test (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `timestamp` INT NOT NULL DEFAULT 0 COMMENT '时间戳'
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

